#!/usr/bin/env bun
// Generate plugins/conin/skills/conin/SKILL.md from the LIVE host-agnostic preprompt (ADR 0020).
//
// The skill is NEVER hand-authored: it is the served `GET /v1/instructions` body wrapped in a thin trigger. Re-run this
// on every release so the plugin can never drift from the app — there is exactly one copy of "who Conin is", and it
// lives in app/src/app.ts (CONIN_SYSTEM), projected over REST. This script is the marketplace repo's only build step.
//
//   bun scripts/build-skill.ts                 # against production
//   CONIN_BASE=http://localhost:8787 bun scripts/build-skill.ts   # against a local app

const BASE = (process.env.CONIN_BASE ?? "https://construction-intelligence.saastemly.com").replace(/\/$/, "");
const OUT = new URL("../plugins/conin/skills/conin/SKILL.md", import.meta.url).pathname;

const res = await fetch(`${BASE}/v1/instructions`);
if (!res.ok) { console.error(`✗ GET ${BASE}/v1/instructions → ${res.status}`); process.exit(1); }
const doc = (await res.json()) as { instructions: string; quickstart?: string; auth?: string; entrypoints?: { mcp?: string; openapi?: string } };
if (!doc.instructions || doc.instructions.length < 500) { console.error("✗ instructions missing or implausibly short"); process.exit(1); }

// The skill's `description` is what Claude reads to decide WHEN to invoke it — it must name the triggers (the deliverables
// + the domain) without restating the whole preprompt. The body is the trigger preamble + the served preprompt verbatim.
const description =
  "Operate Conin (Construction Intelligence) for MENA construction & real-estate projects: generate decision-grade " +
  "deliverables — feasibility studies, residual land value, cost plans, IPC/mostakhlas payment certificates, retention " +
  "& advance recovery, variation registers & quotations, dayworks, claims & loss-and-expense, tender evaluations, " +
  "final accounts, FIDIC contract data, BOQ readiness/audit. Use whenever the user wants to model, cost, value, " +
  "certify, reconcile, or audit a construction project. Deterministic-first: every figure is SOURCED or ASSUMED.";

const body = [
  "You are operating **Conin — Construction Intelligence**, exposed to you as the `conin` MCP server.",
  "",
  "**Connect first.** If the Conin tools aren't available yet, you'll be prompted to log in (browser OAuth) on first tool use — tell the user, then proceed once connected. Conin meters compute against the org's prepaid balance.",
  "",
  "**The one rule:** use ONLY Conin's tools for any construction figure. Never invent, estimate, or guess a number — call a tool and report exactly what it returns, flagging each value as SOURCED (from a document) or ASSUMED (a prior/default). Any ASSUMED figure caps a deliverable at PROVISIONAL; say so.",
  "",
  doc.quickstart ? `**Quickstart:** ${doc.quickstart}` : "",
  "",
  "---",
  "",
  "Below are Conin's own operating instructions (served from the app, the single source of truth). Follow them as written:",
  "",
  doc.instructions,
].filter((l) => l !== "").join("\n");

const md = `---
name: conin
description: ${JSON.stringify(description)}
---

<!-- GENERATED by scripts/build-skill.ts from ${BASE}/v1/instructions — DO NOT EDIT BY HAND. Re-run on release. -->

${body}
`;

await Bun.write(OUT, md);
console.log(`✓ wrote ${OUT} (${md.length} chars) from ${BASE}/v1/instructions`);
